# Configuration de l'application
spring.application.name=quizz-app
server.port=${PORT:8080}

# Configuration Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuration des ressources statiques
spring.web.resources.static-locations=classpath:/static/,classpath:/META-INF/resources/webjars/

# R\u00e9seau
spring.cloud.inetutils.preferred-networks=192.168.|10.0.|127.0.
server.port=${PORT:10000}